# Generated by Django 2.2.7 on 2019-11-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('pulse_date', models.DateField()),
                ('num_volunteers', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
