# Generated by Django 2.2.7 on 2019-11-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='community_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community', to='outreach.Organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='lafayette_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lafayette', to='outreach.Organization'),
        ),
    ]
