# Generated by Django 2.2.7 on 2019-11-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_auto_20191110_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=150),
        ),
    ]
