# Generated by Django 2.2.7 on 2019-11-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_auto_20191122_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='num_volunteers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Volunteers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pulse_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pulse Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='community_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community', to='outreach.Organization', verbose_name='Community Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculty_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='people.Person', verbose_name='Faculty Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lafayette_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lafayette', to='outreach.Organization', verbose_name='Lafayette Organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='people.Person', verbose_name='Student Partner'),
        ),
    ]
