# Generated by Django 2.2.7 on 2019-11-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_auto_20191122_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='num_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Members'),
        ),
    ]
