# Generated by Django 2.2.7 on 2019-11-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0008_auto_20191125_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='num_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Members'),
        ),
    ]
