# Generated by Django 2.2.7 on 2019-12-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0009_auto_20191125_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='people.Person', verbose_name='Student Partner'),
        ),
    ]
