# Generated by Django 2.2.7 on 2019-12-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_auto_20191203_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='community_partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Community Organization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community', to='outreach.Organization', verbose_name='Community Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculty_partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='people.Person', verbose_name='Faculty Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lafayette_organization',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('type', 'Club'), ('type', 'Course'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lafayette', to='outreach.Organization', verbose_name='Lafayette Organization'),
        ),
    ]
