# Generated by Django 2.2.7 on 2019-11-10 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_facultytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='facultytype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Community Member', 'Community Member')], max_length=100),
        ),
    ]
