# Generated by Django 2.2.7 on 2019-11-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='faculty_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.FacultyType'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
