# Generated by Django 2.2.7 on 2019-11-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20191122_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='faculty_type',
        ),
        migrations.AddField(
            model_name='facultytype',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
    ]
