# Generated by Django 2.2.7 on 2019-11-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20191122_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
    ]
