# Generated by Django 2.2.7 on 2019-11-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_remove_person_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultytype',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Department'),
        ),
        migrations.AddField(
            model_name='person',
            name='faculty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.FacultyType'),
        ),
    ]
