# Generated by Django 2.2.7 on 2019-11-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20191122_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faculty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.FacultyType', verbose_name='Faculty Type'),
        ),
    ]
