# Generated by Django 2.2.7 on 2019-11-24 20:51

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20191124_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
